[package]
name = "y2021"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indicatif = "0.17.8"
itertools = "0.12.1"
aoc_macros = { path = "../aoc_macros" }
regex = "1.10.4"
